default:
	pdflatex --file-line-error Chapter\ 1\ notes.tex
	pdflatex --file-line-error Chapter\ 2\ notes.tex
	pdflatex --file-line-error Chapter\ 3\ notes.tex
	pdflatex --file-line-error Chapter\ 4\ notes.tex
	pdflatex --file-line-error Chapter\ 5\ notes.tex
	pdflatex --file-line-error Chapter\ 6\ notes.tex
	pdflatex --file-line-error Chapter\ 7\ notes.tex
	pdflatex --file-line-error Chapter\ 8\ notes.tex
	pdflatex --file-line-error Chapter\ 9\ notes.tex
	pdflatex --file-line-error Chapter\ 10\ notes.tex
	pdflatex --file-line-error Casella\ and\ Berger\ notes.tex
	rm Chapter\ 1\ notes.aux
	rm Chapter\ 1\ notes.log
	rm Chapter\ 1\ notes.out
	rm Chapter\ 2\ notes.aux
	rm Chapter\ 2\ notes.log
	rm Chapter\ 2\ notes.out
	rm Chapter\ 3\ notes.aux
	rm Chapter\ 3\ notes.log
	rm Chapter\ 3\ notes.out
	rm Chapter\ 4\ notes.aux
	rm Chapter\ 4\ notes.log
	rm Chapter\ 4\ notes.out
	rm Chapter\ 5\ notes.aux
	rm Chapter\ 5\ notes.log
	rm Chapter\ 5\ notes.out
	rm Chapter\ 6\ notes.aux
	rm Chapter\ 6\ notes.log
	rm Chapter\ 6\ notes.out
	rm Chapter\ 7\ notes.aux
	rm Chapter\ 7\ notes.log
	rm Chapter\ 7\ notes.out
	rm Chapter\ 8\ notes.aux
	rm Chapter\ 8\ notes.log
	rm Chapter\ 8\ notes.out
	rm Chapter\ 9\ notes.aux
	rm Chapter\ 9\ notes.log
	rm Chapter\ 9\ notes.out
	rm Chapter\ 10\ notes.aux
	rm Chapter\ 10\ notes.log
	rm Chapter\ 10\ notes.out
	rm Casella\ and\ Berger\ notes.aux
	rm Casella\ and\ Berger\ notes.log
	rm Casella\ and\ Berger\ notes.out

